package org.excilys.computer_database.persistence;

public enum RequestName {

  LIST_COMPUTERS,
  LIST_COMPANIES,
  COMPUTER_DETAILS,
  COMPANY,
  CREATE_COMPUTER,
  UPDATE_COMPUTER,
  DELETE_COMPUTER,
  CHECK_ID_COMPUTER,
  CHECK_ID_COMPANY,
  COUNT_COMPUTERS,
  LIST_COMPUTERS_AT_PAGE

}
