package org.excilys.computer_database.ui;

public enum WSMenuOption {
  AUTHENTICATE,
  REGISTER,
  CHANGE_PASSWORD,
  LIST_COMPUTERS,
  CREATE_COMPUTER,
  UPDATE_COMPUTER,
  DELETE_COMPUTER,
  LIST_COMPANIES,
  CREATE_COMPANY,
  UPDATE_COMPANY,
  DELETE_COMPANY,
  DONE
}
